# Generated by Django 4.2.7 on 2023-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('officer', 'Officer'), ('user', 'User')], default=3, max_length=10),
        ),
    ]
