# Generated by Django 4.2.7 on 2023-11-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('officer', 'Officer'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
