# Generated by Django 4.2.7 on 2023-11-20 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('Type_of_complaint', models.CharField(choices=[('Street Lights', 'Street Lights'), ('Water Pipe Leakage', 'Water Pipe Leakage'), ('Drainage', 'Drainage'), ('Roads', 'Roads'), ('Other', 'Other')], max_length=200, null=True)),
                ('Description', models.TextField(max_length=4000, null=True)),
                ('Time', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Solved'), (2, 'InProgress'), (3, 'Pending')], default=3)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
