# Generated by Django 4.2.7 on 2023-11-24 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_complaint_type_of_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('', 'Select Type of Complaint'), ('Street Lights', 'Street Lights'), ('Water Pipe Leakage', 'Water Pipe Leakage'), ('Drainage', 'Drainage'), ('Roads', 'Roads'), ('Other', 'Other')], default='Type of complaint', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=25)),
                ('Message', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
